Name: Yilin Pu

Github Username: pyl32

USC ID: 2952467624

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

### 1. An interesting task in machine learning is classification of time series. In this problem,we will classify the activities of humans based on time series obtained by a Wireless Sensor Network.
#### (a) Download the AReM data from: https://archive.ics.uci.edu/ml/datasets/Activity+Recognition+system+based+on+Multisensor+data+fusion+\%28AReM\%29 . The dataset contains 7 folders that represent seven types of activities. In each folder, there are multiple files each of which represents an instant of a human performing an activity.1 Each file containis 6 time series collected from activities of the same person, which are called avg rss12, var rss12, avg rss13, var rss13, vg rss23, and ar rss23. There are 88 instances in the dataset, each of which contains 6 time series and each time series has 480 consecutive values.

In [2]:
data = '../data/ARem'
activities = ['bending1', 'walking', 'bending2', 'standing', 'sitting', 'lying', 'cycling']

#### (b) Keep datasets 1 and 2 in folders bending1 and bending 2, as well as datasets 1,2, and 3 in other folders as test data and other datasets as train data.

In [3]:
train = []
test = []
for root,dirs,files in os.walk(data):
    if not dirs:
        activity = root.split('/')[3]
        for f in files:
            num = re.findall('\d+',f)[0]
            path = root + '/' + f
            if activity in ['bending1','bending2']:
                if int(num) <= 2:
                    test.append(path)
                else:
                    train.append(path)
            else:
                if int(num) <= 3:
                    test.append(path)
                else:
                    train.append(path)
print(train)
print(test)

['../data/ARem/bending1/dataset7.csv', '../data/ARem/bending1/dataset6.csv', '../data/ARem/bending1/dataset4.csv', '../data/ARem/bending1/dataset5.csv', '../data/ARem/bending1/dataset3.csv', '../data/ARem/walking/dataset7.csv', '../data/ARem/walking/dataset6.csv', '../data/ARem/walking/dataset4.csv', '../data/ARem/walking/dataset5.csv', '../data/ARem/walking/dataset10.csv', '../data/ARem/walking/dataset11.csv', '../data/ARem/walking/dataset13.csv', '../data/ARem/walking/dataset12.csv', '../data/ARem/walking/dataset15.csv', '../data/ARem/walking/dataset14.csv', '../data/ARem/walking/dataset8.csv', '../data/ARem/walking/dataset9.csv', '../data/ARem/bending2/dataset6.csv', '../data/ARem/bending2/dataset4.csv', '../data/ARem/bending2/dataset5.csv', '../data/ARem/bending2/dataset3.csv', '../data/ARem/standing/dataset7.csv', '../data/ARem/standing/dataset6.csv', '../data/ARem/standing/dataset4.csv', '../data/ARem/standing/dataset5.csv', '../data/ARem/standing/dataset10.csv', '../data/ARem/standing/dataset11.csv', '../data/ARem/standing/dataset13.csv', '../data/ARem/standing/dataset12.csv', '../data/ARem/standing/dataset15.csv', '../data/ARem/standing/dataset14.csv', '../data/ARem/standing/dataset8.csv', '../data/ARem/standing/dataset9.csv', '../data/ARem/sitting/dataset7.csv', '../data/ARem/sitting/dataset6.csv', '../data/ARem/sitting/dataset4.csv', '../data/ARem/sitting/dataset5.csv', '../data/ARem/sitting/dataset10.csv', '../data/ARem/sitting/dataset11.csv', '../data/ARem/sitting/dataset13.csv', '../data/ARem/sitting/dataset12.csv', '../data/ARem/sitting/dataset15.csv', '../data/ARem/sitting/dataset14.csv', '../data/ARem/sitting/dataset8.csv', '../data/ARem/sitting/dataset9.csv', '../data/ARem/lying/dataset7.csv', '../data/ARem/lying/dataset6.csv', '../data/ARem/lying/dataset4.csv', '../data/ARem/lying/dataset5.csv', '../data/ARem/lying/dataset10.csv', '../data/ARem/lying/dataset11.csv', '../data/ARem/lying/dataset13.csv', '../data/ARem/lying/dataset12.csv', '../data/ARem/lying/dataset15.csv', '../data/ARem/lying/dataset14.csv', '../data/ARem/lying/dataset8.csv', '../data/ARem/lying/dataset9.csv', '../data/ARem/cycling/dataset7.csv', '../data/ARem/cycling/dataset6.csv', '../data/ARem/cycling/dataset4.csv', '../data/ARem/cycling/dataset5.csv', '../data/ARem/cycling/dataset10.csv', '../data/ARem/cycling/dataset11.csv', '../data/ARem/cycling/dataset13.csv', '../data/ARem/cycling/dataset12.csv', '../data/ARem/cycling/dataset15.csv', '../data/ARem/cycling/dataset14.csv', '../data/ARem/cycling/dataset8.csv', '../data/ARem/cycling/dataset9.csv']
['../data/ARem/bending1/dataset1.csv', '../data/ARem/bending1/dataset2.csv', '../data/ARem/walking/dataset1.csv', '../data/ARem/walking/dataset2.csv', '../data/ARem/walking/dataset3.csv', '../data/ARem/bending2/dataset1.csv', '../data/ARem/bending2/dataset2.csv', '../data/ARem/standing/dataset1.csv', '../data/ARem/standing/dataset2.csv', '../data/ARem/standing/dataset3.csv', '../data/ARem/sitting/dataset1.csv', '../data/ARem/sitting/dataset2.csv', '../data/ARem/sitting/dataset3.csv', '../data/ARem/lying/dataset1.csv', '../data/ARem/lying/dataset2.csv', '../data/ARem/lying/dataset3.csv', '../data/ARem/cycling/dataset1.csv', '../data/ARem/cycling/dataset2.csv', '../data/ARem/cycling/dataset3.csv']

#### (c) Feature Extraction Classification of time series usually needs extracting features from them. In this problem, we focus on time-domain features. 

##### i. Research what types of time-domain features are usually used in time series classification and list them (examples are minimum, maximum, mean, etc).

The time-domain features are minimum, maximum, mean, median, standard deviation, quantiles, skewness, kurtosis and higher order moments.

##### ii. Extract the time-domain features minimum, maximum, mean, median, standard deviation, first quartile, and third quartile for all of the 6 time series in each instance. You are free to normalize/standardize features or use them directly.

In [98]:
col = ['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23']
features = ['min','max','mean','median','std','1st_quartile','3rd_quartile']
total_features = [] 
i=1
for i in range(1,7):
    for feat in features:
        total_features.append(feat+str(i))
    i += 1
instances1 = []
for path in train_path:
    data1 = pd.read_csv(path,header=None,skiprows=[0,1,2,3,4],error_bad_lines=False, warn_bad_lines=False)
    if len(data1.iloc[6,:]) == 1:
        data1 = pd.read_csv(path, skiprows=5, header=None,sep="\s+",error_bad_lines=False, warn_bad_lines=False)
    data1.columns = col
    data_feature = data1.describe()
    instance1 = []
    for j in range(1,7):
        values = data_feature.iloc[:,j].values
        instance1.append(values[3])
        instance1.append(values[7])
        instance1.append(values[1])
        instance1.append(values[5])
        instance1.append(values[2])
        instance1.append(values[4])
        instance1.append(values[6])
    instances1.append(instance1)              
df_train = pd.DataFrame(instances1, columns=total_features)
df_train

,min1,max1,mean1,median1,std1,1st_quartile1,3rd_quartile1,min2,max2,mean2,...,std5,1st_quartile5,3rd_quartile5,min6,max6,mean6,median6,std6,1st_quartile6,3rd_quartile6
0,36.25,48.00,43.969125,44.50,1.618364,43.310,44.67,0.0,1.50,0.413125,...,3.318301,20.5000,23.7500,0.0,2.96,0.555313,0.490,0.487826,0.0000,0.830
1,37.00,48.00,43.454958,43.25,1.386098,42.500,45.00,0.0,1.58,0.378083,...,2.488862,22.2500,24.0000,0.0,5.26,0.679646,0.500,0.622534,0.4300,0.870
2,33.00,47.75,42.179813,43.50,3.670666,39.150,45.00,0.0,3.00,0.696042,...,3.849448,30.4575,36.3300,0.0,2.18,0.613521,0.500,0.524317,0.0000,1.000
3,33.00,45.75,41.678063,41.75,2.243490,41.330,42.75,0.0,2.83,0.535979,...,2.411026,28.4575,31.2500,0.0,1.79,0.383292,0.430,0.389164,0.0000,0.500
4,35.00,47.40,43.954500,44.33,1.558835,43.000,45.00,0.0,1.70,0.426250,...,1.999604,35.3625,36.5000,0.0,1.79,0.493292,0.430,0.513506,0.0000,0.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,18.50,44.25,35.752354,36.00,4.614802,33.000,39.33,0.0,12.60,3.328104,...,3.120057,14.0000,18.0625,0.0,9.39,3.069667,2.770,1.748326,1.7975,4.060
65,24.25,45.00,37.177042,36.25,3.581301,34.500,40.25,0.0,8.58,2.374208,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.900
66,23.33,43.50,36.248768,36.75,3.824632,33.415,39.25,0.0,9.71,2.737307,...,3.617405,15.7500,21.0000,0.0,11.15,3.532463,3.110,1.965267,2.1700,4.625
67,26.25,44.25,36.957458,36.29,3.434863,34.500,40.25,0.0,8.64,2.420083,...,2.851673,14.0000,18.2500,0.0,8.34,2.934625,2.525,1.631380,1.6600,4.030
68,27.75,44.67,37.142359,36.33,3.762442,34.000,40.50,0.0,10.76,2.422150,...,2.687173,15.0000,18.7500,0.0,8.75,2.825720,2.590,1.637312,1.5900,3.740

In [99]:
instances2 = []

for path in test_path:
    data2 = pd.read_csv(path,header=None,skiprows=[0,1,2,3,4],error_bad_lines=False, warn_bad_lines=False)
    data2.columns = col
    data_feature = data2.describe()
    instance2 = []
    for j in range(1,7):
        values = data_feature.iloc[:,j].values
        instance2.append(values[3])
        instance2.append(values[7])
        instance2.append(values[1])
        instance2.append(values[5])
        instance2.append(values[2])
        instance2.append(values[4])
        instance2.append(values[6])
    instances2.append(instance2)              
df_test = pd.DataFrame(instances2, columns=total_features)
df_test

,min1,max1,mean1,median1,std1,1st_quartile1,3rd_quartile1,min2,max2,mean2,...,std5,1st_quartile5,3rd_quartile5,min6,max6,mean6,median6,std6,1st_quartile6,3rd_quartile6
0,37.25,45.00,40.624792,40.500,1.476967,39.2500,42.0000,0.0,1.30,0.358604,...,2.188449,33.0000,36.0000,0.0,1.92,0.570583,0.430,0.582915,0.0000,1.300
1,38.00,45.67,42.812812,42.500,1.435550,42.0000,43.6700,0.0,1.22,0.372438,...,1.995255,32.0000,34.5000,0.0,3.11,0.571083,0.430,0.601010,0.0000,1.300
2,19.33,43.50,34.227771,35.500,4.889576,30.5000,37.7500,0.0,14.50,3.995729,...,3.092094,14.7500,18.6700,0.0,9.74,3.394125,3.100,1.792090,2.1050,4.425
3,12.50,45.00,33.509729,34.125,4.850923,30.5000,36.7500,0.0,13.05,4.450771,...,3.133564,14.6275,18.7500,0.0,8.96,3.378479,3.085,1.787360,2.0600,4.440
4,15.00,46.75,34.660583,35.000,5.315110,31.0000,38.2500,0.0,13.44,4.200896,...,3.155015,14.2500,18.5000,0.0,8.99,3.244396,3.000,1.630983,2.1200,4.240
5,12.75,51.00,24.562958,24.250,3.737514,23.1875,26.5000,0.0,6.87,0.590833,...,3.693786,20.5000,27.0000,0.0,4.97,0.700188,0.500,0.693720,0.4300,0.870
6,0.00,42.75,27.464604,28.000,3.583582,25.5000,30.0000,0.0,7.76,0.449708,...,5.053642,15.0000,20.7500,0.0,6.76,1.122125,0.830,1.012342,0.4700,1.300
7,33.33,48.00,44.334729,45.000,2.476940,42.2500,46.5000,0.0,3.90,0.432958,...,5.401794,9.3300,17.7500,0.0,5.02,0.933000,0.830,0.673609,0.4700,1.250
8,35.50,46.25,43.174938,43.670,1.989052,42.5000,44.5000,0.0,2.12,0.506583,...,2.983976,12.7500,16.5000,0.0,5.72,0.911979,0.830,0.666161,0.4700,1.220
9,32.75,47.00,42.760563,44.500,3.398919,41.3300,45.3725,0.0,3.34,0.486167,...,4.296574,13.0000,18.5650,0.0,5.73,0.842271,0.710,0.722165,0.4300,1.090
10,33.25,48.00,42.363563,43.000,2.068247,42.0000,43.5000,0.0,4.44,0.492563,...,4.956821,10.1875,17.6900,0.0,6.02,1.034021,0.830,0.985627,0.4700,1.250
11,37.00,50.75,45.917667,45.635,1.089027,45.0000,46.5000,0.0,4.87,0.324542,...,3.585511,16.5000,21.0000,0.0,7.22,0.904604,0.710,0.896171,0.4300,1.120
12,44.50,46.75,45.239667,45.000,0.429915,45.0000,45.3300,0.0,1.00,0.172958,...,2.945840,17.6275,21.0000,0.0,8.20,0.837250,0.710,0.835344,0.4300,1.120
13,23.50,30.00,27.716375,27.500,1.442253,27.0000,29.0000,0.0,1.79,0.363688,...,4.074511,5.5000,10.7500,0.0,4.50,0.734271,0.710,0.613688,0.4300,1.000
14,24.75,48.33,44.182937,48.000,7.495615,48.0000,48.0000,0.0,3.11,0.101875,...,3.274539,2.0000,5.5425,0.0,3.91,0.692771,0.500,0.675781,0.3225,0.940
15,48.00,48.25,48.004167,48.000,0.032038,48.0000,48.0000,0.0,0.43,0.007167,...,3.268502,4.6700,10.0000,0.0,2.50,0.641229,0.500,0.388372,0.4600,0.830
16,24.25,45.00,37.177042,36.250,3.581301,34.5000,40.2500,0.0,8.58,2.374208,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.900
17,28.75,44.75,37.561188,36.875,3.226507,35.2500,40.2500,0.0,9.91,2.080688,...,2.727377,18.0000,21.5000,0.0,9.62,2.765896,2.450,1.769203,1.4100,3.770
18,22.00,44.67,37.058708,36.000,3.710180,34.5000,40.0625,0.0,14.17,2.438146,...,3.537144,16.0000,21.0000,0.0,8.55,2.983750,2.570,1.815730,1.5000,4.150

In [100]:
instances = instances1 + instances2
df = pd.DataFrame(instances, columns=total_features)
print(df)

     min1   max1      mean1  median1      std1  1st_quartile1  3rd_quartile1  \
0   36.25  48.00  43.969125   44.500  1.618364          43.31        44.6700
1   37.00  48.00  43.454958   43.250  1.386098          42.50        45.0000
2   33.00  47.75  42.179813   43.500  3.670666          39.15        45.0000
3   33.00  45.75  41.678063   41.750  2.243490          41.33        42.7500
4   35.00  47.40  43.954500   44.330  1.558835          43.00        45.0000
..    ...    ...        ...      ...       ...            ...            ...
83  24.75  48.33  44.182937   48.000  7.495615          48.00        48.0000
84  48.00  48.25  48.004167   48.000  0.032038          48.00        48.0000
85  24.25  45.00  37.177042   36.250  3.581301          34.50        40.2500
86  28.75  44.75  37.561188   36.875  3.226507          35.25        40.2500
87  22.00  44.67  37.058708   36.000  3.710180          34.50        40.0625

    min2   max2     mean2  ...      std5  1st_quartile5  3rd_quartile5  min6  \
0    0.0   1.50  0.413125  ...  3.318301        20.5000        23.7500   0.0
1    0.0   1.58  0.378083  ...  2.488862        22.2500        24.0000   0.0
2    0.0   3.00  0.696042  ...  3.849448        30.4575        36.3300   0.0
3    0.0   2.83  0.535979  ...  2.411026        28.4575        31.2500   0.0
4    0.0   1.70  0.426250  ...  1.999604        35.3625        36.5000   0.0
..   ...    ...       ...  ...       ...            ...            ...   ...
83   0.0   3.11  0.101875  ...  3.274539         2.0000         5.5425   0.0
84   0.0   0.43  0.007167  ...  3.268502         4.6700        10.0000   0.0
85   0.0   8.58  2.374208  ...  2.890347        17.9500        21.7500   0.0
86   0.0   9.91  2.080688  ...  2.727377        18.0000        21.5000   0.0
87   0.0  14.17  2.438146  ...  3.537144        16.0000        21.0000   0.0

    max6     mean6  median6      std6  1st_quartile6  3rd_quartile6
0   2.96  0.555313     0.49  0.487826         0.0000           0.83
1   5.26  0.679646     0.50  0.622534         0.4300           0.87
2   2.18  0.613521     0.50  0.524317         0.0000           1.00
3   1.79  0.383292     0.43  0.389164         0.0000           0.50
4   1.79  0.493292     0.43  0.513506         0.0000           0.94
..   ...       ...      ...       ...            ...            ...
83  3.91  0.692771     0.50  0.675781         0.3225           0.94
84  2.50  0.641229     0.50  0.388372         0.4600           0.83
85  9.34  2.921729     2.50  1.852600         1.5000           3.90
86  9.62  2.765896     2.45  1.769203         1.4100           3.77
87  8.55  2.983750     2.57  1.815730         1.5000           4.15

[88 rows x 42 columns]

##### iii. Estimate the standard deviation of each of the time-domain features you extracted from the data. Then, use Python’s bootstrapped or any other method to build a 90% bootsrap confidence interval for the standard deviation of each feature.

In [101]:
f_std = df.describe().loc['std']
print(f_std)

min1             9.569975
max1             4.394362
mean1            5.335700
median1          5.440054
std1             1.772185
1st_quartile1    6.153874
3rd_quartile1    5.138925
min2             0.000000
max2             5.062729
mean2            1.574198
median2          1.412293
std2             0.884137
1st_quartile2    0.946386
3rd_quartile2    2.125399
min3             2.956462
max3             4.875137
mean3            4.008228
median3          4.036396
std3             0.946670
1st_quartile3    4.220658
3rd_quartile3    4.171628
min4             0.000000
max4             2.183625
mean4            1.166178
median4          1.145985
std4             0.458283
1st_quartile4    0.843405
3rd_quartile4    1.552504
min5             6.124001
max5             5.741238
mean5            5.675543
median5          5.813782
std5             1.024918
1st_quartile5    6.096465
3rd_quartile5    5.531720
min6             0.045838
max6             2.518921
mean6            1.154889
median6          1.086474
std6             0.517651
1st_quartile6    0.758687
3rd_quartile6    1.523739
Name: std, dtype: float64

In [105]:
from sklearn.utils import resample

total_bootstrap = []

for i in range(1000):
    df_bootstrap = resample(df, replace=True, n_samples=df.shape[0])
    df_std_bootstrap = df_bootstrap.describe().loc['std']
    total_bootstrap.append(list(df_std_bootstrap))
total_bootstrap = pd.DataFrame(total_bootstrap, columns=total_features)

int_5, int_95 = [], []
for i in range(0,42):
    col = total_bootstrap.iloc[:,i]
    int1 = np.percentile(col, 5)
    int2 = np.percentile(col, 95)
    int_5.append(int1) 
    int_95.append(int2)
interval = [int_5,int_95]
interval_90 = pd.DataFrame(interval, columns=total_features)
print(interval_90)

        min1      max1     mean1   median1      std1  1st_quartile1  \
0   8.289523  3.353345  4.687150  4.741967  1.555183       5.546278
1  10.757909  5.321904  5.899244  6.008797  1.947822       6.670411

   3rd_quartile1  min2      max2     mean2  ...      std5  1st_quartile5  \
0       4.353995   0.0  4.630960  1.395319  ...  0.812397       4.769689
1       5.813004   0.0  5.412786  1.704145  ...  1.210708       7.306750

   3rd_quartile5      min6      max6     mean6   median6      std6  \
0       4.312724  0.000000  2.244420  1.062293  0.993470  0.479341
1       6.590477  0.078476  2.759177  1.212988  1.144104  0.545958

   1st_quartile6  3rd_quartile6
0       0.689599       1.402332
1       0.809436       1.597101

[2 rows x 42 columns]

##### iv. Use your judgement to select the three most important time-domain features (one option may be min, mean, and max).

I choose min, max, and mean since the quantiles doesnt have much differences. The max and min can shows the range/wide of distribution, and the mean shows the average of the distribution.

### 2. ISLR 3.7.4

#### (a)

The cubic regression should have a smaller residual sum of squares than the linear regression. Or the cubic regression will have the same RSS as the linear regression.

#### (b)

Because the polynomial model tends to overfit the data, the test RSS for the cubic regression should be greater than the linear.

#### (c)

The training RSS for the cubic regression would be lower than linear because higher flexibility makes it fitted points closer to the observed ones.

#### (d)

The linear regression test RSS should be lower than the cubic when it is closer to linear than cubic

### References

https://docs.python.org/3/library/os.html?highlight=walk#os.walk

https://stats.stackexchange.com/questions/50807/features-for-time-series-classification

https://scikit-learn.org/stable/modules/generated/sklearn.utils.resample.html